test:
    build: .
    environment:
        NODE_ENV: "development"
        EMAIL_HOST: "localhost"
        EMAIL_PASSWORD: "email password"
        EMAIL_USERNAME: "email username"
        EMAIL_PORT: 1231
        EMAIL_FROM: "testing@66pix.com"
    volumes:
        - .:/srv/www
    dns:
        - 8.8.8.8
        - 9.9.9.9
